require conf/distro/poky-atmel.conf

DISTRO = "poky-mobileye"

KERNEL_MODULE_AUTOLOAD += "atmel_usba_udc"
KERNEL_MODULE_AUTOLOAD += "g_ether"
KERNEL_MODULE_PROBECONF += "g_ether"
module_conf_g_ether = "options g_ether host_addr=c2:c0:74:d1:cA:81 dev_addr=32:4a:c3:9f:1e:38"




