# This grammar copied from 
# 
# == GENIVI/CANdb project ==
# (Licensed under MPL2.0)
#
# This grammar modified for the projects need and to meet
#
# == Vector DBC File Format (Version 01/2007) ==
#
# TODO review, refactor, rearange
grammar                 <- spacing _ version _ comment* ns_comment bs? _ (bu / bu_sl)? _ val_table? _ message* _ bo_tx_bu* _ cm* cm_bu* _ (cm_bo _ / cm_sg _)* _ (ba_def_str / ba_def_num / ba_def_enum / ba_def_rel)* _ (ba_def_def / ba_def_def_rel)* _ ba* _ ba_bu* _ ba_bo* _ ba_sg* _ ba_rel* vals* sig_val* _ EndOfFile

spacing                 <- (s / comment)*
ns_comment              <- (ns? / comment)? NewLine*
version                 <- < 'VERSION' s* phrase s* > NewLine
ns                      <- < 'NS_' s* ':' s* NewLine symbol_name* > NewLine
bs                      <- < 'BS_' s* ':' s* NewLine symbol_name* > NewLine
bu                      <- < 'BU_' s* ':' s* NewLine symbol_name* > NewLine
bu_sl                   <- < 'BU_' s* ':' s* NAME (s* NAME)* > NewLine
val_table               <- val_entry* NewLine
message                 <- 'BO_' s* number s* NAME ':' s number s ECU_NAME _ signal* (TrailingSpace / _ )
bo_tx_bu                <- < 'BO_TX_BU_' s* number s* ':' s* ECU_NAME (',' ECU_NAME)* ';' > NewLine
cm                      <- < 'CM_' s* phrase > ';' NewLine
cm_bu                   <- < 'CM_' s* 'BU_' s* NAME s* phrase > ';' NewLine
cm_bo                   <- < 'CM_' s* 'BO_' s* integer s* phrase > ';' NewLine
cm_sg                   <- < 'CM_' s* 'SG_' s* integer s* NAME s* phrase > ';' NewLine*
ba_def_str              <- (< 'BA_DEF_' s* (('BO_' / 'SG_' / 'BU_') s*)? phrase s* 'STRING' s* ';' > (NewLine / s* comment) ) / comment
ba_def_num              <- (< 'BA_DEF_' s* (('BO_' / 'SG_' / 'BU_') s*)? phrase s* ('INT' / 'HEX') s* number s* number ';' > (NewLine / s* comment) ) / comment
ba_def_enum             <- (< 'BA_DEF_' s* (('BO_' / 'SG_' / 'BU_') s*)? phrase s* 'ENUM' s* ENUM_VAL';' > (NewLine / s* comment) ) / comment
ba_def_def              <- < 'BA_DEF_DEF_' s* phrase s* (phrase / number ) ';' > NewLine
ba                      <- < 'BA_' s* phrase s* (phrase / number ) ';' > NewLine
ba_bu                   <- < 'BA_' s* phrase s* 'BU_' s* NAME s* (phrase / number) ';' > NewLine
ba_bo                   <- < 'BA_' s* phrase s* 'BO_' s* number s* (phrase / number) s* ';' > NewLine
ba_sg                   <- < 'BA_' s* phrase s* 'SG_' s* number s* NAME s* number s* ';' > NewLine
# ignore ba_def_rel for now
ba_def_rel              <- 'BA_DEF_REL_' (!NewLine .)* NewLine
# ignore ba_def_def_rel for now
ba_def_def_rel          <- 'BA_DEF_DEF_REL_' (!NewLine .)* NewLine
# ignore ba_rel for now
ba_rel                  <- 'BA_REL_' (!NewLine .)* NewLine

vals                    <- < 'VAL_' s* number s* NAME s* (number_phrase_pair)* ';' > NewLine*
comment                 <- '//' (!NewLine .)* NewLine
sig_val                 <- < 'SIG_VALTYPE_' s* number s* NAME s* ':' s* number ';' > NewLine

signal                  <- < s* 'SG_' s* NAME s* mux? mux_ndx? s* ':' s* number '|' number '@' number sign s* '(' number ',' s* number ')' s* '[' number '|' number ']' s* phrase s* ECU_NAME (',' ECU_NAME)* > NewLine
val_entry               <- < 'VAL_TABLE_' s* NAME s (number_phrase_pair)* ';' > NewLine
number_phrase_pair      <- number s* phrase s*
phrase                  <- < '"' (!'"' .)* '"' >
sign                    <- < [-+] > _
NAME                   <- [a-zA-Z0-9'_']+
ECU_NAME               <- [a-zA-Z0-9'_']+
ENUM_VAL                <- (!';' .)+
number                  <- float / integer 
integer                 <- < sign? [0-9]+ > _
float                   <- < sign? ([0-9]+'.')?[0-9]+('E' sign [0-9]+)? > _
symbol_name             <- < s* NAME > NewLine
mux                     <- 'M'
mux_ndx                 <- 'm'< [0-9]+ >

EndOfFile               <- !.

s                       <- [ \t]
NewLine                 <- [\r\n]

TrailingSpace           <- ' '* _

~_                      <- [\t\r\n]*
~__                     <- ![a-zA-Z0-9]
